### ISSUE TITLE
Custom Presentation Controller

### ISSUE THREAD

**Issue by mergesort** [serp1412/LazyTransitions#4]
Hi there,

This library is really neat, I'm enjoying trying it out, but running into an issue that I can't seem to think of a way around. I'm attempting to achieve an effect like this. I'm trying to make LazyTransitioner and a `UIPresentationController` work nicely together to achieve an effect like this.

![Semi-modal](https://cloud.githubusercontent.com/assets/716513/25870233/5f93df70-34d1-11e7-8ccf-b6936e12cd56.png)

I tried following the README's advice of doing this instead of forward the `animator` and `interactor` properties, but it's not working because of the situation below.

```swift
func animationController(forDismissed dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? {
    // ... pass the animator
    return transitioner.animator
}
    
func interactionControllerForDismissal(using animator: UIViewControllerAnimatedTransitioning) -> UIViewControllerInteractiveTransitioning? {
    // ... pass the interactor
    return transitioner.interactor
}
```

But the problem is that I still need my own implementation of `func animationController(forDismissed dismissed: UIViewController)` to properly dismiss.

```swift
func animationController(forDismissed dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? {
    return MyCustomTransition(isReversed: true, duration: 0.4)
}
```

My suggestion would be to be able to pass in a custom `UIPresentationController` which can be used in conjunction with the transitioner, though I'm a bit fuzzy on the implementation.

I would love to figure out if this is currently possible, and if not, find out if it's possible to add in the future.

Thanks a lot!

**Comment by serp1412** [comment]
Hey @mergesort,

Thanks for trying it out.

I assume the way to go in your case is to make your custom transition (`MyCustomTransition`) conform to protocol `TransitionAnimatorType` then try to pass it in the `init` method of `LazyTransitioner`.

`let transitioner = LazyTransitioner(animator: myCustomAnimator)`

Then you can remove the delegate methods for dismiss because in the internal implementation your custom animator will be used.

I haven't tried to use `LazyTransitioner` with other custom animators but you could check and see what happens 🙂 

Also, if you don't mind, share a repo with your problem and I can try to play around with it as well.

Cheers,
Serghei

**Comment by mergesort** [comment]
Thanks a lot for the advice. I tried out turning my `UIViewControllerAnimatedTransitioning` into a `TransitionAnimatorType`, and don't think it's quite working as intended. 

[Here's](https://github.com/mergesort/LazyTransitionsTest) a repo where I'm working on it right now.

There's a couple of things not functioning as I'd like.

Currently the presenting view controller extends the full way, unlike the picture in my original comment, where it only goes partially up the screen. If you look at the `DimmmedBackgroundPresentationController` in the added project, it would allow to specify the desired size, and a dimmed background to match. I didn't see a way to incorporate that at all.

The dismiss is a bit jarring, but I did not make any changes to accommodate for that, but I'm not sure about that.

Feel free to tell me everything I did wrong, I'd love to figure out how to incorporate this. 🙃

Thanks again!

**Comment by serp1412** [comment]
@mergesort sorry for the wait. I've figured out how to make it work with your presentation controller and make it appear with a smaller height. The only problem is that the interactive transition doesn't cancel properly if you drag it just a little bit, it always decides that it's finished. I need to check why that happens. Will try to get back to you with a finalized solution soon

**Comment by mergesort** [comment]
@serp1412 I totally appreciate the work. I'm going to try implementing it again next week, so please take your time and don't worry too much about me. 🙂

**Comment by mergesort** [comment]
@serp1412 I know I said I wouldn't mind if you took some time, but I was just wondering if you had a chance to look into this a bit more. 😅 

Thanks a lot!

**Comment by serp1412** [comment]
@mergesort Sorry man, very busy time in my life. But I did finish it up. Check out [my fork](https://github.com/serp1412/LazyTransitionsTest) from your repo. The last commit shows what had to be changed to get this to work.

Let me know if it works as you expected

**Comment by mergesort** [comment]
Of course your priorities come first, I completely understand. I'm very appreciative for you taking the time to help me with this.

I just checked it out, and it looks great, and now I understand what you meant (along with catching my bug that made the dismiss transition wonky). I'm going to try integrating it back into my larger project today, I just wanted to say thank you very much for all the help.

**Comment by serp1412** [comment]
Good to hear 👍 Was nice learning that my framework plays nicely with `UIPresentationController` 🙂
