### ISSUE TITLE
UI flickering issue

### ISSUE THREAD

**Issue by phiren** [serp1412/LazyTransitions#5]
Hello,

I have tried with this code, it is really nice but facing one problem. The UI flickers when swipe to dismiss.

Same happening while tapping on button "Dismiss Demo" and try to swipe left to right to dismiss. The view sometime flickers.

Not sure where it goes wrong, Was checking how other library does it smooth like https://github.com/lkzhao/Hero

But not able to find better solution for it, I have found something in their code but not sure how it is working, here is the screenshot.

File: HeroTransition+Start.swift
![screen shot 2017-11-08 at 2 24 27 pm](https://user-images.githubusercontent.com/8377260/32539944-219ccfce-c491-11e7-8754-afe4306dab13.png)

Please let me know if required more info.

Thanks
Hiren

**Comment by serp1412** [comment]
Hey Hiren!

Thanks for pointing this out. I really should fix issue and groom the repo a little bit. It's been a while.

I'll try to do it in the nearest future.

Cheers,
Serghei

**Comment by phiren** [comment]
Hello Serghei,

I am trying from last two days to fix that, but not finding better solution. Do you have any idea why it is happening? I tried by console log from different methods of gesture and checked if there might be happening something wrong, but it is not. The updating progress with gesture and all good as per the console log.

I need this animation without that glitch. Can you please help me here to solve it? I need it as early as possible.

Thanks
Hiren

**Comment by serp1412** [comment]
Hey Hiren,

Sorry for the super late response.
I've looked into the bug and it seems like a UIKit issue. I could reproduce it in the most barebones custom dismiss transition implementation. So it's not coming from my framework.

I've opened a radar for Apple and will update here on its progress.

You probably don't care at this point, but I thought it's still worth writing here 😊 

Cheers,
Serghei

**Comment by serp1412** [comment]
This issue is no longer reproducible on iOS 12.1 (probably even sooner 😊 )
